version: "3.9"
services:
  nginx:
    image: "nginx:1.18.0-alpine"
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/home/tuan/app/src